name: source_deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/244800070903/locations/global/workloadIdentityPools/example-pool/providers/example-gh-provider'
        service_account: 'my-service-account@glasnt-ghatest-1146.iam.gserviceaccount.com'


    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        source: '.'
        region: australia-southeast1
        service: 'bottle'